/**
 * Scripted days: the regression net for the whole day loop.
 *
 * GENERATED by `npx vite-node scripts/generate-scripted-days.ts`. Do not edit
 * by hand — regenerate, and treat any change to an expected summary as a
 * deliberate rule change to review.
 */
import type { DaySummary } from '../game.js';

export interface ScriptedDay {
  readonly name: string;
  readonly seed: number;
  /** Run-length encoded action tokens; expand with `decodeLog`. */
  readonly actions: readonly string[];
  readonly expected: DaySummary;
}

export const SCRIPTED_DAYS: readonly ScriptedDay[] = [
  {
    name: 'perfect day',
    seed: 20260901,
    actions: ['start', 's:c0r4', 's:c0r6', 's:c0r5', 's:c0r0', 's:c0r1', 's:c1r4', 's:c0r2', 's:c0r3', 's:c1r0', 's:c1r1', 's:c1r2', 's:c1r6', 's:c1r3', 's:c1r5', 's:c2r4', 's:c2r5', 't250*3', 's:c0r4', 't250*10', 's:c1r4', 't250*6', 's:c0r4', 't250*5', 's:c1r6', 't250*9', 's:c0r3', 't250*16', 's:c0r3', 't250', 's:c0r6', 't250*9', 's:c1r1', 't250*17', 's:c0r1', 't250*3', 's:c0r6', 't250*8', 's:c2r5', 't250*16', 's:c0r5', 't250*8', 's:c1r0', 't250*5', 's:c0r0', 't250*9', 's:c1r5', 't250*13', 's:c0r0', 't250*3', 's:c2r4', 't250*11', 's:c0r2', 't250*14', 's:c1r2', 't250*7', 's:c1r3', 's:c0r0', 's:c0r3', 's:c0r4', 's:c0r6'],
    expected: {
      served: 20,
      hinted: 0,
      walked: 0,
      refused: 0,
      unplaced: 0,
      wrongTaps: 0,
      score: 4000,
      timeMs: 43250,
      slotOutcomes: {
        c0r0: 'perfect',
        c0r1: 'perfect',
        c0r2: 'perfect',
        c0r3: 'perfect',
        c0r4: 'perfect',
        c0r5: 'perfect',
        c0r6: 'perfect',
        c1r0: 'perfect',
        c1r1: 'perfect',
        c1r2: 'perfect',
        c1r3: 'perfect',
        c1r4: 'perfect',
        c1r5: 'perfect',
        c1r6: 'perfect',
        c2r0: 'none',
        c2r1: 'none',
        c2r2: 'none',
        c2r3: 'none',
        c2r4: 'perfect',
        c2r5: 'perfect',
        c2r6: 'none',
      },
    },
  },
  {
    name: 'hinted day',
    seed: 20260902,
    actions: ['start', 's:c0r0', 's:c0r4', 's:c0r5', 's:c0r1', 's:c0r6', 's:c0r2', 's:c0r3', 's:c1r4', 's:c1r5', 's:c1r0', 's:c1r1', 's:c1r2', 's:c1r6', 's:c1r3', 's:c2r0', 's:c2r1', 's:c0r0', 's:c0r2', 't250*10', 's:c0r0', 's:c1r5', 't250*9', 's:c0r0', 's:c1r6', 't250*8', 's:c0r1', 's:c0r0', 't250*8', 's:c0r1', 's:c1r5', 't250*13', 's:c0r1', 's:c1r0', 't250*3', 's:c0r1', 's:c1r4', 't250*9', 's:c0r1', 's:c1r1', 't250*15', 's:c0r1', 's:c0r0', 't250*5', 's:c0r3', 's:c0r1', 't250*12', 's:c0r3', 's:c0r1', 't250*11', 's:c0r3', 's:c0r5', 't250*9', 's:c0r3', 's:c0r4', 't250*4', 's:c0r3', 's:c1r2', 't250*7', 's:c0r3', 's:c1r3', 't250*15', 's:c0r6', 's:c0r3', 't250*10', 's:c0r6', 's:c2r0', 't250*6', 's:c0r6', 's:c2r1', 't250*100', 's:c0r0', 's:c0r1', 's:c0r6', 's:c1r5'],
    expected: {
      served: 18,
      hinted: 15,
      walked: 1,
      refused: 1,
      unplaced: 0,
      wrongTaps: 18,
      score: 3025,
      timeMs: 63500,
      slotOutcomes: {
        c0r0: 'hinted',
        c0r1: 'hinted',
        c0r2: 'hinted',
        c0r3: 'hinted',
        c0r4: 'hinted',
        c0r5: 'hinted',
        c0r6: 'walked',
        c1r0: 'hinted',
        c1r1: 'hinted',
        c1r2: 'hinted',
        c1r3: 'hinted',
        c1r4: 'hinted',
        c1r5: 'hinted',
        c1r6: 'hinted',
        c2r0: 'hinted',
        c2r1: 'hinted',
        c2r2: 'none',
        c2r3: 'none',
        c2r4: 'none',
        c2r5: 'none',
        c2r6: 'none',
      },
    },
  },
  {
    name: 'walked and refused day',
    seed: 20260903,
    actions: ['start', 's:c0r0', 's:c0r6', 's:c0r1', 's:c1r6', 's:c0r2', 's:c2r6', 's:c0r4', 's:c0r3', 't250*360', 's:c0r0', 's:c0r1', 's:c0r2', 's:c0r3', 's:c0r4', 's:c0r6', 's:c1r6', 's:c2r6'],
    expected: {
      served: 0,
      hinted: 0,
      walked: 8,
      refused: 4,
      unplaced: 8,
      wrongTaps: 0,
      score: 0,
      timeMs: 90000,
      slotOutcomes: {
        c0r0: 'walked',
        c0r1: 'walked',
        c0r2: 'walked',
        c0r3: 'walked',
        c0r4: 'walked',
        c0r5: 'none',
        c0r6: 'walked',
        c1r0: 'none',
        c1r1: 'none',
        c1r2: 'none',
        c1r3: 'none',
        c1r4: 'none',
        c1r5: 'none',
        c1r6: 'walked',
        c2r0: 'none',
        c2r1: 'none',
        c2r2: 'none',
        c2r3: 'none',
        c2r4: 'none',
        c2r5: 'none',
        c2r6: 'walked',
      },
    },
  },
];
