/**
 * Scripted weeks: the regression net for the run around the days.
 *
 * GENERATED by `npm run gen:fixtures`. Do not edit by hand — regenerate, and
 * treat any change to an expected week as a deliberate rule change to review.
 */
import type { WeekStatus } from '../week.js';

export interface ScriptedWeekDay {
  readonly dayIndex: number;
  readonly score: number;
  readonly timeMs: number;
  readonly stars: number;
  readonly starsLost: number;
  readonly incidents: { readonly unplaced: number; readonly refused: number; readonly walked: number };
}

export interface ScriptedWeek {
  readonly name: string;
  readonly seed: number;
  /** One run-length encoded action log per day played. */
  readonly logs: readonly (readonly string[])[];
  readonly expected: {
    readonly status: WeekStatus;
    readonly stars: number;
    readonly total: number;
    readonly days: readonly ScriptedWeekDay[];
  };
}

export const SCRIPTED_WEEKS: readonly ScriptedWeek[] = [
  {
    name: 'a clean week',
    seed: 4242,
    logs: [
      ['start', 's:c0r0', 's:c0r4', 's:c0r1', 's:c0r2', 's:c0r5', 's:c1r4', 's:c0r3', 's:c1r0', 's:c0r1', 't250*11', 's:c1r4', 't250*27', 's:c0r3', 't250*13', 's:c0r4', 't250*16', 's:c1r0', 't250*15', 's:c0r5', 't250*26', 's:c0r0', 't250*26', 's:c0r2'],
      ['start', 's:c0r4', 's:c0r0', 's:c0r1', 's:c0r2', 's:c0r6', 's:c0r3', 's:c1r0', 's:c1r6', 's:c1r1', 't250*3', 's:c1r1', 't250*4', 's:c0r3', 't250*15', 's:c0r3', 't250*24', 's:c0r6', 't250*3', 's:c0r2', 't250*11', 's:c0r5', 't250*20', 's:c0r4', 't250*15', 's:c0r1', 't250*8', 's:c0r0', 't250*21', 's:c1r0', 't250*2', 's:c1r6', 's:c0r3', 's:c0r5'],
      ['start', 's:c0r4', 's:c0r6', 's:c0r0', 's:c0r5', 's:c0r1', 's:c1r6', 's:c0r2', 's:c0r3', 's:c2r6', 's:c1r4', 's:c1r0', 's:c1r5*2', 't250*15', 's:c1r5', 't250*8', 's:c0r5', 't250*13', 's:c0r2', 't250*13', 's:c1r4', 't250*8', 's:c0r2', 't250*7', 's:c2r6', 't250*14', 's:c0r0', 't250*16', 's:c0r1', 't250*15', 's:c1r0', 't250*5', 's:c0r4', 't250*8', 's:c0r4', 't250*12', 's:c0r6', 't250*15', 's:c1r6', 't250*11', 's:c0r3', 's:c0r2', 's:c0r4', 's:c1r5'],
      ['start', 's:c0r4', 's:c0r0', 's:c0r6', 's:c0r5', 's:c0r1', 's:c0r2', 's:c0r3', 's:c1r6', 's:c1r0', 's:c1r1', 's:c1r2', 's:c1r3', 's:c2r0', 's:c1r4', 's:c1r5', 's:c1r3', 't250*11', 's:c0r5', 't250*5', 's:c1r2', 't250*12', 's:c2r0', 't250*15', 's:c0r5', 't250', 's:c0r0', 't250*15', 's:c1r0', 't250*6', 's:c1r1', 't250*10', 's:c0r2', 't250*8', 's:c1r6', 't250*10', 's:c0r1*2', 't250*15', 's:c0r0', 't250*7', 's:c0r1', 't250*7', 's:c0r2', 't250*9', 's:c1r4', 't250*14', 's:c0r4', 't250*4', 's:c0r6', 't250*16', 's:c0r3', 't250*6', 's:c1r5', 's:c0r0', 's:c0r1', 's:c0r2', 's:c0r5'],
      ['start', 's:c0r0', 's:c0r6', 's:c1r6', 's:c0r1', 's:c0r2', 's:c0r3', 's:c2r6', 's:c3r6', 's:c0r4', 's:c0r5', 's:c1r0', 's:c1r4', 's:c1r1', 's:c1r2', 's:c1r5', 's:c2r4', 's:c2r5', 's:c3r4', 's:c3r5', 's:c1r3', 't250*4', 's:c1r3', 't250*6', 's:c1r5', 't250*9', 's:c1r0', 't250*3', 's:c1r2', 't250*13', 's:c1r6', 't250', 's:c3r6', 't250*13', 's:c0r0', 't250*2', 's:c1r5', 't250*11', 's:c2r5', 't250*6', 's:c0r6', 't250*10', 's:c0r0', 't250*6', 's:c0r6', 't250*11', 's:c3r4', 't250*2', 's:c1r6', 't250*8', 's:c0r5', 't250*9', 's:c0r4', 't250*8', 's:c0r4', 't250*11', 's:c1r4', 't250*3', 's:c0r3', 't250*11', 's:c1r1', 't250*4', 's:c2r6', 't250*10', 's:c3r5', 't250*7', 's:c0r2', 't250*8', 's:c0r5', 't250*8', 's:c0r1', 't250*11', 's:c2r4', 's:c0r0', 's:c0r4', 's:c0r5', 's:c0r6', 's:c1r5', 's:c1r6'],
      ['start', 's:c0r0', 's:c0r1', 's:c0r4', 's:c0r2', 's:c0r3', 's:c1r0', 's:c0r5', 's:c1r4', 's:c1r1', 's:c1r5', 's:c0r6', 's:c2r4', 's:c1r6', 's:c2r5', 's:c3r4', 's:c3r5', 's:c1r2', 's:c4r4', 's:c1r3', 's:c2r0', 's:c2r1', 's:c2r2', 's:c4r5', 's:c2r6', 's:c2r3', 's:c3r6', 's:c4r6', 's:c3r5', 't250*4', 's:c1r0', 't250*8', 's:c3r5', 't250*10', 's:c2r1', 't250*6', 's:c2r5', 't250*3', 's:c1r4', 't250*9', 's:c3r4', 't250*6', 's:c3r6', 't250*9', 's:c0r2', 't250*5', 's:c0r2', 't250*8', 's:c0r1', 't250*6', 's:c1r2', 't250*4', 's:c2r4', 't250*9', 's:c0r4', 't250*7', 's:c0r1', 't250*5', 's:c0r5', 't250*4', 's:c1r5', 't250*9', 's:c1r1*2', 't250*5', 's:c1r6', 't250*10', 's:c4r4', 't250*3', 's:c0r4', 't250*10', 's:c2r6', 't250*2', 's:c2r3', 't250*10', 's:c1r3', 't250*4', 's:c0r6', 't250*9', 's:c4r5', 't250*6', 's:c0r0', 't250*3', 's:c0r0', 't250*6', 's:c0r5', 't250*8', 's:c4r6', 't250*10', 's:c2r0', 't250*7', 's:c0r6', 't250*5', 's:c1r4', 't250*7', 's:c0r3', 't250*6', 's:c2r2', 's:c0r0', 's:c0r1', 's:c0r2', 's:c0r4', 's:c0r5', 's:c0r6', 's:c1r4', 's:c3r5'],
    ],
    expected: {
      status: 'done',
      stars: 3,
      total: 22800,
      days: [
      {
        dayIndex: 0,
        score: 1600,
        timeMs: 33500,
        stars: 3,
        starsLost: 0,
        incidents: { unplaced: 0, refused: 0, walked: 0 },
      },
      {
        dayIndex: 1,
        score: 2200,
        timeMs: 31500,
        stars: 3,
        starsLost: 0,
        incidents: { unplaced: 0, refused: 0, walked: 0 },
      },
      {
        dayIndex: 2,
        score: 3000,
        timeMs: 40000,
        stars: 3,
        starsLost: 0,
        incidents: { unplaced: 0, refused: 0, walked: 0 },
      },
      {
        dayIndex: 3,
        score: 3800,
        timeMs: 42750,
        stars: 3,
        starsLost: 0,
        incidents: { unplaced: 0, refused: 0, walked: 0 },
      },
      {
        dayIndex: 4,
        score: 5200,
        timeMs: 48750,
        stars: 3,
        starsLost: 0,
        incidents: { unplaced: 0, refused: 0, walked: 0 },
      },
      {
        dayIndex: 5,
        score: 7000,
        timeMs: 55750,
        stars: 3,
        starsLost: 0,
        incidents: { unplaced: 0, refused: 0, walked: 0 },
      },
      ],
    },
  },
  {
    name: 'a week that runs out of stars on Friday',
    seed: 777,
    logs: [
      ['start', 's:c0r4', 's:c0r5', 's:c0r0', 's:c0r6', 's:c1r4', 's:c0r1', 's:c1r6', 's:c1r5', 's:c1r6', 't250*10', 's:c0r1', 't250*30', 's:c0r0', 't250*8', 's:c1r5', 't250*29', 's:c0r6', 't250*18', 's:c0r5', 't250*20', 's:c1r4', 't250*13', 's:c0r4'],
      ['start', 's:c0r6', 's:c1r6', 's:c0r0', 's:c0r4', 's:c0r1', 's:c0r5', 's:c0r2', 's:c1r4', 's:c0r3', 's:c0r6', 't250*15', 's:c0r2', 't250*8', 's:c0r4', 't250*23', 's:c0r2', 't250*12', 's:c0r0', 't250*2', 's:c1r4', 't250*14', 's:c0r5', 't250*17', 's:c1r6', 't250*12', 's:c0r3', 't250*16', 's:c0r1', 't250*18', 's:c0r4', 's:c0r2', 's:c0r4'],
      ['start', 's:c0r6', 's:c0r4', 's:c0r0', 's:c1r6', 's:c0r5', 's:c0r1', 's:c0r2', 's:c0r3', 's:c2r6', 's:c1r4', 's:c1r5', 't250*100', 's:c1r0', 't250*10', 's:c0r0', 't250*8', 's:c1r4', 't250*18', 's:c0r3', 't250*17', 's:c0r1', 't250*19', 's:c1r5', 't250*7', 's:c1r6', 't250*8', 's:c0r6', 't250*21', 's:c0r5', 't250*6', 's:c2r6', 't250*12', 's:c0r2', 't250*8', 's:c0r0', 't250*15', 's:c0r1', 't250*7', 's:c0r4', 's:c0r0', 's:c0r1', 's:c1r0'],
      ['start', 's:c0r0', 's:c0r4', 's:c0r1', 's:c0r2', 's:c0r6', 's:c0r5', 's:c0r3', 's:c1r4', 's:c1r5', 's:c1r6', 's:c2r6', 's:c1r0', 's:c2r4', 's:c1r1', 't250*104', 's:c0r5', 't250*3', 's:c1r6', 't250*10', 's:c0r6', 't250*12', 's:c0r4*2', 't250*12', 's:c0r2', 't250*4', 's:c2r4', 't250*24', 's:c0r2', 't250*9', 's:c0r0', 't250*5', 's:c1r4', 't250*15', 's:c1r5', 't250*10', 's:c0r0', 't250*10', 's:c1r1', 't250*8', 's:c1r0', 't250*7', 's:c0r4', 't250*8', 's:c2r6', 't250*15', 's:c0r5', 't250*3', 's:c0r1', 't250*16', 's:c0r3', 's:c0r0', 's:c0r2', 's:c0r4', 's:c0r5'],
      ['start', 's:c0r0', 's:c0r4', 's:c0r1', 's:c0r5', 's:c0r2', 's:c0r3', 's:c0r6', 's:c1r0', 's:c1r1', 's:c1r6', 's:c1r2', 's:c1r3', 's:c1r4', 's:c1r5', 's:c2r0', 's:c2r6', 's:c2r1', 's:c2r2', 's:c2r3', 't250*61', 's:c2r4', 't250*9', 's:c1r1', 't250*4', 's:c0r2', 't250*6', 's:c0r3', 't250*13', 's:c2r6', 't250*8', 's:c0r4', 't250*4', 's:c0r1', 't250*8', 's:c0r0', 't250*11', 's:c0r0', 't250*8', 's:c0r4', 't250*7', 's:c2r3', 't250*9', 's:c1r5', 't250*10', 's:c1r6', 't250*7', 's:c2r1', 't250*9', 's:c1r4', 't250*6', 's:c1r3', 't250*14', 's:c1r0', 't250', 's:c1r2', 't250*10', 's:c2r2', 't250*10', 's:c1r4', 't250*5', 's:c2r0', 't250*12', 's:c0r1', 't250*5', 's:c0r2', 't250*10', 's:c0r6', 't250*5', 's:c0r5', 's:c0r0', 's:c0r1', 's:c0r2', 's:c0r4', 's:c1r4', 's:c2r4'],
    ],
    expected: {
      status: 'failed',
      stars: 0,
      total: 15200,
      days: [
      {
        dayIndex: 0,
        score: 1600,
        timeMs: 32000,
        stars: 3,
        starsLost: 0,
        incidents: { unplaced: 0, refused: 0, walked: 0 },
      },
      {
        dayIndex: 1,
        score: 2200,
        timeMs: 34250,
        stars: 3,
        starsLost: 0,
        incidents: { unplaced: 0, refused: 0, walked: 0 },
      },
      {
        dayIndex: 2,
        score: 2800,
        timeMs: 64000,
        stars: 2,
        starsLost: 1,
        incidents: { unplaced: 1, refused: 0, walked: 0 },
      },
      {
        dayIndex: 3,
        score: 3600,
        timeMs: 68750,
        stars: 1,
        starsLost: 1,
        incidents: { unplaced: 1, refused: 0, walked: 0 },
      },
      {
        dayIndex: 4,
        score: 5000,
        timeMs: 63000,
        stars: 0,
        starsLost: 1,
        incidents: { unplaced: 1, refused: 0, walked: 0 },
      },
      ],
    },
  },
];
